// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgbLswFer_vYlLLdirPIEc43RfHKjH_Bk',
    appId: '1:161069182084:web:0084a8c5889aaeb457a6d1',
    messagingSenderId: '161069182084',
    projectId: 'outerhorizons-e92b8',
    authDomain: 'outerhorizons-e92b8.firebaseapp.com',
    storageBucket: 'outerhorizons-e92b8.firebasestorage.app',
    measurementId: 'G-DVMFFQEZKW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsuslUalySGztgcxsLsjCb6pf-MhSksaY',
    appId: '1:161069182084:android:223825119119e7cf57a6d1',
    messagingSenderId: '161069182084',
    projectId: 'outerhorizons-e92b8',
    storageBucket: 'outerhorizons-e92b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4nGsJhJjeD5CECH90ImKAC2m9pJrcN38',
    appId: '1:161069182084:ios:eab22988fe5772eb57a6d1',
    messagingSenderId: '161069182084',
    projectId: 'outerhorizons-e92b8',
    storageBucket: 'outerhorizons-e92b8.firebasestorage.app',
    iosBundleId: 'com.example.outerHorizons',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgbLswFer_vYlLLdirPIEc43RfHKjH_Bk',
    appId: '1:161069182084:web:363bf276758c84cd57a6d1',
    messagingSenderId: '161069182084',
    projectId: 'outerhorizons-e92b8',
    authDomain: 'outerhorizons-e92b8.firebaseapp.com',
    storageBucket: 'outerhorizons-e92b8.firebasestorage.app',
    measurementId: 'G-EMXQ0E3LV2',
  );
}
